AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
  VpcId:
    Type: "AWS::EC2::VPC::Id"
  SubnetId:
    Type: "AWS::EC2::Subnet::Id"
  IncomingIpAddress:
    Type: "String"
    Description: "IP Address for incoming SSH connections"
    Default: "0.0.0.0/0"

Mappings:
  RegionMap:
    eu-west-1:
      amiId: "ami-7000b109"
    ap-southeast-2:
      amiId: "ami-2d5db74f"

Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", amiId]
      InstanceType: t1.micro
      KeyName: !Ref "KeyName"
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref "SecurityGroup"
          SubnetId: !Ref "SubnetId"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow ssh connections from specified CIDR ranges
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref "IncomingIpAddress"

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref "InstanceRole"

  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodeCommitPowerUser"

Outputs:
  PublicDnsName:
    Description: "Public DNS Name for EC2 Instance"
    Value: !GetAtt Ec2Instance.PublicDnsName
